Repository Katello/hammer-cli-katello, pull requests merged in 2018-12, with the labels that each got.

#595 Fixes #25187 Include value for ATTACHED & QUANTITY
  lib/hammer_cli_katello/activation_key.rb
Labels: Needs re-review, Needs testing

#603 Bump to 0.16.0 for Katello 3.10
  .travis.yml
  hammer_cli_katello.gemspec
  lib/hammer_cli_katello/version.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#604 Add Katello 3.10 apipie cache
  test/data/3.10/foreman_api.json
  test/test_helper.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#605 Bump version to 0.17-master
  lib/hammer_cli_katello/version.rb
  test/data/3.10/foreman_api.json
  test/test_helper.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#607 Fixes #25682 - Update export tar name to cvname-versionid
  lib/hammer_cli_katello/content_view_version.rb
  test/functional/content_view/version/export_test.rb
Labels: Needs testing, Not yet reviewed

#608 Refs #22253 - Fixes after option validation is mixed with sources
  lib/hammer_cli_katello/activation_key.rb
  lib/hammer_cli_katello/content_view.rb
  lib/hammer_cli_katello/content_view_name_resolvable.rb
  lib/hammer_cli_katello/content_view_purge.rb
  lib/hammer_cli_katello/content_view_version.rb
  lib/hammer_cli_katello/erratum.rb
  lib/hammer_cli_katello/file.rb
  lib/hammer_cli_katello/filter.rb
  lib/hammer_cli_katello/host_collection.rb
  lib/hammer_cli_katello/hostgroup_extensions.rb
  lib/hammer_cli_katello/id_name_options_validator.rb
  lib/hammer_cli_katello/lifecycle_environment.rb
  lib/hammer_cli_katello/lifecycle_environment_name_resolvable.rb
  lib/hammer_cli_katello/package.rb
  lib/hammer_cli_katello/puppet_environment_name_resolvable.rb
  lib/hammer_cli_katello/repository.rb
  lib/hammer_cli_katello/repository_scoped_to_product.rb
  test/unit/id_name_options_validator_test.rb
Labels: Needs testing, Not yet reviewed

#610 Fixes #25728 - Show Recurring Logic Id
  lib/hammer_cli_katello/sync_plan.rb
Labels: Needs testing, Not yet reviewed
