Repository Katello/hammer-cli-katello, pull requests merged in 2018-09, with the labels that each got.

#581 Fixes #24806: bound h-c-f version in gemspec
  .travis.yml
  hammer_cli_katello.gemspec
Labels: Needs testing, Not yet reviewed

#565 [WIP] refs #24051 - add docker tags whitelist
  lib/hammer_cli_katello/repository.rb
Labels: Waiting on contributor

#583 [CP] Picks for Katello 3.7.1 & version bump
  lib/hammer_cli_katello/foreman_search_options_creators.rb
  lib/hammer_cli_katello/host_content_source_options.rb
  lib/hammer_cli_katello/version.rb
  test/functional/content_view/version/incremental_update_test.rb
Labels: Needs testing, Not yet reviewed

#580 Make a test file non-executable
  test/functional/content_view/version/incremental_update_test.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#585 Match hammer-cli/h-c-foreman master version scheme
  lib/hammer_cli_katello/version.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#576 Fixes #24408 - Added module-stream command
  lib/hammer_cli_katello.rb
  lib/hammer_cli_katello/associating_commands.rb
  lib/hammer_cli_katello/erratum.rb
  lib/hammer_cli_katello/file.rb
  lib/hammer_cli_katello/id_resolver.rb
  lib/hammer_cli_katello/module_stream.rb
  lib/hammer_cli_katello/module_stream_profile.rb
  lib/hammer_cli_katello/ostree_branch.rb
  lib/hammer_cli_katello/package_group.rb
  lib/hammer_cli_katello/puppet_module.rb
  lib/hammer_cli_katello/repository.rb
  lib/hammer_cli_katello/repository_scoped_to_product.rb
  lib/hammer_cli_katello/search_options_creators.rb
  test/data/3.8/foreman_api.json
  test/functional/module_stream/info_test.rb
  test/functional/module_stream/list_test.rb
  test/functional/package_group/list_test.rb
Labels: Requires Katello PR

#587 Refs #24569 - Add 3.9 apidata & tests for cv publish version.
  test/data/3.9/foreman_api.json
  test/functional/content_view/publish_test.rb
  test/test_helper.rb
Labels: Needs testing, Not yet reviewed, Requires Katello PR

#586 Update license and homepage in the gemspec
  hammer_cli_katello.gemspec
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#584 Fixes #24894 - Support for cron expressions
  lib/hammer_cli_katello/sync_plan.rb
  test/functional/sync_plan/create_test.rb
  test/functional/sync_plan/delete_test.rb
  test/functional/sync_plan/update_test.rb
Labels: Needs testing, Not yet reviewed, Requires Katello PR

#590 fixes #25027 - fixes search for image by name
  lib/hammer_cli_katello/foreman_search_options_creators.rb
Labels: Needs testing, Not yet reviewed

#591 pin hammer foreman_tasks to pre 0.0.13
  hammer_cli_katello.gemspec
  lib/hammer_cli_katello/version.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor
