Repository Katello/hammer-cli-katello, pull requests merged in 2019-10, with the labels that each got.

#596 Refs #3036 - Ping command
  lib/hammer_cli_katello.rb
  lib/hammer_cli_katello/command_extensions.rb
  lib/hammer_cli_katello/command_extensions/ping.rb
  lib/hammer_cli_katello/ping.rb
  lib/hammer_cli_katello/status.rb
  test/functional/ping_test.rb
Labels: Ready for merge

#699 Fixes #27947 - Allow duplicate file uploads
  lib/hammer_cli_katello/repository.rb
  test/data/3.14/foreman_api.json
  test/functional/activation_key/subscriptions_test.rb
  test/functional/repository/update_test.rb
  test/functional/repository/upload_test.rb
  test/functional/subscription/list_test.rb
Labels: Needs testing, Not yet reviewed, Requires Katello PR

#681 Fixes #27712 - module stream rules
  lib/hammer_cli_katello/filter_rule.rb
Labels: Needs testing, Waiting on contributor

#702 Fix ping test on master
  release_notes.md
  test/data/3.14/foreman_api.json
Labels: Ready for merge

#703 Bump version to 0.21
  lib/hammer_cli_katello/version.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#704 Bump to 0.20.0 for Katello 3.14
  .travis.yml
  hammer_cli_katello.gemspec
  lib/hammer_cli_katello/version.rb
Labels: Ready for merge

#705 Update test data/helper for Katello 3.15
  test/data/3.15/foreman_api.json
  test/test_helper.rb
Labels: Not yet reviewed
