Repository Katello/hammer-cli-katello, pull requests merged in 2019-06, with the labels that each got.

#653 Fixes #27094 - hammer host list including errata info
  lib/hammer_cli_katello/host_extensions.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#654 Fixes #27096 - hammer host-collection hosts including erratas info
  lib/hammer_cli_katello/host_collection.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#655 Fixes #27101 - Content View version export error message fix
  lib/hammer_cli_katello/cv_import_export_helper.rb
  test/functional/content_view/version/export_test.rb
Labels: Needs testing, Not yet reviewed

#651 Fixes #27039 - Content View version Export Condition Fix
  lib/hammer_cli_katello/content_view_version.rb
  test/functional/content_view/version/export_test.rb
Labels: Needs testing
