Repository Katello/hammer-cli-katello, pull requests merged in 2019-08, with the labels that each got.

#673 Fix tests on master
  test/functional/content_view/publish_test.rb
  test/functional/host/extensions/update_test.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#672 fixes #27504 - Hammer Package Info to show all data
  lib/hammer_cli_katello/package.rb
Labels: Needs testing, Not yet reviewed

#678 Bump to 0.19.0 for Katello 3.13
  .travis.yml
  hammer_cli_katello.gemspec
  lib/hammer_cli_katello/version.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#679 Bump master to 0.20
  hammer_cli_katello.gemspec
  lib/hammer_cli_katello/version.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#680 Update apipie cache to 3.14
  test/data/3.14/foreman_api.json
  test/test_helper.rb
Labels: Ready for merge

#675 Fixes #27466 - Allow Hammer to update cv version descriptions
  lib/hammer_cli_katello/content_view_version.rb
  test/functional/content_view/version/update_test.rb
Labels: Needs re-review

#674 Refs #26135 - Add srpm listing/info command and tests
  lib/hammer_cli_katello.rb
  lib/hammer_cli_katello/srpm.rb
  test/functional/srpm/list_test.rb
Labels: Ready for merge

#676 Fixes #27523 - removing options from ContentView update
  lib/hammer_cli_katello/content_view.rb
  test/functional/content_view/create_test.rb
  test/functional/content_view/update_test.rb
Labels: Needs re-review, Needs testing

#691 Fix broken tests on master from Foreman Hammer Change
  test/functional/content_view/publish_test.rb
  test/functional/host/extensions/update_test.rb
Labels: Requires Hammer PR, Waiting on contributor

#693 [CP] Refs #26135 - Add srpm listing/info command and tests
  lib/hammer_cli_katello.rb
  lib/hammer_cli_katello/srpm.rb
  test/functional/srpm/list_test.rb
Labels: Ready for merge

#694 Update hammer-cli-katello to 0.19.1
  lib/hammer_cli_katello/version.rb
Labels: Not yet reviewed
