Repository Katello/hammer-cli-katello, pull requests merged in 2019-07, with the labels that each got.

#656 Fixes #27187 - Fixing Content View version Export for default organiz…
  lib/hammer_cli_katello/cv_import_export_helper.rb
Labels: Needs testing, Not yet reviewed

#629 Refs #23204 - Consistent puppet environment naming in hammer
  lib/hammer_cli_katello.rb
  lib/hammer_cli_katello/activation_key.rb
  lib/hammer_cli_katello/capsule.rb
  lib/hammer_cli_katello/command_extensions.rb
  lib/hammer_cli_katello/command_extensions/lifecycle_environment.rb
  lib/hammer_cli_katello/command_extensions/lifecycle_environments.rb
  lib/hammer_cli_katello/commands.rb
  lib/hammer_cli_katello/content_view.rb
  lib/hammer_cli_katello/content_view_version.rb
  lib/hammer_cli_katello/host_extensions.rb
  lib/hammer_cli_katello/host_subscription.rb
  lib/hammer_cli_katello/hostgroup_extensions.rb
  lib/hammer_cli_katello/id_resolver.rb
  lib/hammer_cli_katello/lifecycle_environment_name_mapping.rb
  lib/hammer_cli_katello/option_sources.rb
  lib/hammer_cli_katello/option_sources/lifecycle_environment_params.rb
  lib/hammer_cli_katello/puppet_environment_name_resolvable.rb
  lib/hammer_cli_katello/repository.rb
  test/functional/repository/list_test.rb
Labels: Needs testing, Not yet reviewed, Requires Hammer PR

#660 Refs #27213 - Add update filter test
  test/functional/content_view/filter/update_test.rb
Labels: Not yet reviewed

#661 [CP] Fixes #27187 - Fixing CV version export for default org view
  lib/hammer_cli_katello/cv_import_export_helper.rb
Labels: Needs testing, Not yet reviewed

#662 Fixes #27261 - export-legacy should not be described as deprecated
  lib/hammer_cli_katello/content_view_version.rb
Labels: Needs testing, Not yet reviewed

#664 fixes #27230 - SysPurpose act key info
  lib/hammer_cli_katello/activation_key.rb
  test/functional/activation_key/data/activation_key.json
  test/functional/activation_key/info_test.rb
Labels: Needs testing, Not yet reviewed

#663 fixes #24170 - SysPurpose on content host info
  lib/hammer_cli_katello/host_extensions.rb
  test/functional/host/extensions/data/host.json
  test/functional/host/extensions/info_test.rb
Labels: Needs testing, Not yet reviewed

#666 Fixes #27374 - Add export-default to export default cv like CDN
  lib/hammer_cli_katello/content_view_version.rb
  test/functional/content_view/version/default_export_test.rb
Labels: Needs testing

#667 [CP] Refs #23204 - Consistent puppet environment naming in hammer (#629)
  lib/hammer_cli_katello.rb
  lib/hammer_cli_katello/activation_key.rb
  lib/hammer_cli_katello/capsule.rb
  lib/hammer_cli_katello/command_extensions.rb
  lib/hammer_cli_katello/command_extensions/lifecycle_environment.rb
  lib/hammer_cli_katello/command_extensions/lifecycle_environments.rb
  lib/hammer_cli_katello/commands.rb
  lib/hammer_cli_katello/content_view.rb
  lib/hammer_cli_katello/content_view_version.rb
  lib/hammer_cli_katello/host_extensions.rb
  lib/hammer_cli_katello/host_subscription.rb
  lib/hammer_cli_katello/hostgroup_extensions.rb
  lib/hammer_cli_katello/id_resolver.rb
  lib/hammer_cli_katello/lifecycle_environment_name_mapping.rb
  lib/hammer_cli_katello/option_sources.rb
  lib/hammer_cli_katello/option_sources/lifecycle_environment_params.rb
  lib/hammer_cli_katello/puppet_environment_name_resolvable.rb
  lib/hammer_cli_katello/repository.rb
  test/functional/repository/list_test.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#668 Bump to 0.18.1
  lib/hammer_cli_katello/version.rb
Labels: Ready for merge

#669 bump to 0.18.2
  lib/hammer_cli_katello/version.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#665 Refs #26135 - Allow hammer to send off content-type
  lib/hammer_cli_katello/repository.rb
  test/data/3.13/foreman_api.json
  test/functional/repository/upload_test.rb
Labels: Requires Katello PR
