Repository Katello/hammer-cli-katello, pull requests merged in 2019-01, with the labels that each got.

#606 Fixes #25628: Resolve repo set id by org/product
  lib/hammer_cli_katello/repository_set.rb
  lib/hammer_cli_katello/search_options_creators.rb
  test/data/3.11/foreman_api.json
  test/functional/repository_set/available_repositories_test.rb
  test/functional/repository_set/disable_test.rb
  test/functional/repository_set/enable_test.rb
  test/functional/repository_set/info_test.rb
  test/functional/repository_set/list_test.rb
  test/functional/repository_set/repository_set_helpers.rb
  test/functional/test_helper.rb
  test/test_helper.rb
Labels: Needs re-review, Needs testing, Waiting on contributor

#612 Fixes #25805 - Display correct value for redhat repo
  lib/hammer_cli_katello/repository.rb
Labels: Needs testing, Not yet reviewed

#613 Fixes #25813 Docker tag info in man pages very vague
  lib/hammer_cli_katello/repository.rb
Labels: Needs testing, Not yet reviewed

#616 Fixes #25857 - Make export dir always absolute
  lib/hammer_cli_katello/content_view_version.rb
Labels: Needs testing, Not yet reviewed

#619 Fixes #24750 - Search options for compute profiles
  lib/hammer_cli_katello/foreman_search_options_creators.rb
  test/unit/search_options_creators_test.rb
Labels: Needs testing, Not yet reviewed

#618 Fixes #25861 - Update download policy to include background
  lib/hammer_cli_katello/content_view_version.rb
  test/functional/content_view/version/export_test.rb
Labels: Needs testing, Not yet reviewed

#617 Fixes #25845 - Module stream info for erratum
  lib/hammer_cli_katello/erratum.rb
  lib/hammer_cli_katello/erratum_info_command.rb
  lib/hammer_cli_katello/host_errata.rb
  test/functional/erratum/erratum_helpers.rb
  test/functional/erratum/info_test.rb
  test/functional/host/errata/info_test.rb
Labels: Needs testing, Not yet reviewed

#621 Bump to 0.17.0 for Katello 3.11
  .travis.yml
  hammer_cli_katello.gemspec
  lib/hammer_cli_katello/version.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#622 Bump to 0.18-master
  lib/hammer_cli_katello/version.rb
  test/data/3.12/foreman_api.json
  test/test_helper.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#623 Fixes #25915 - Skip white list info on repos
  lib/hammer_cli_katello/repository.rb
Labels: Needs testing, Not yet reviewed

#624 Fixes #25919 - Add error message when import cv is nil
  lib/hammer_cli_katello/content_view_version.rb
  test/functional/content_view/version/import_test.rb
Labels: Needs testing, Not yet reviewed

#625 Fixes #25932 - Prevent reimport of same CV version
  lib/hammer_cli_katello/content_view_version.rb
  test/functional/content_view/version/import_test.rb
Labels: Needs testing, Not yet reviewed

#626 Fixes #25947 - Prevent Mirror repos from being imported
  lib/hammer_cli_katello/content_view_version.rb
  lib/hammer_cli_katello/cv_import_export_helper.rb
  test/functional/content_view/version/import_test.rb
Labels: Needs testing, Not yet reviewed
