Repository Katello/hammer-cli-katello, pull requests merged in 2019-09, with the labels that each got.

#696 Fixes #27807 - Prevent timeout during CVV import
  lib/hammer_cli_katello/content_view_version.rb
Labels: Not yet reviewed

#695 Fixes #25588 - updates content-view-id description
  lib/hammer_cli_katello/content_view.rb
Labels: Needs testing, Not yet reviewed

#688 Fixes #27717 - Support pulp3 content uploads
  lib/hammer_cli_katello/repository.rb
Labels: Ready for merge

#644 Refs #25878 - Rename tags
  lib/hammer_cli_katello/output/formatters.rb
Labels: Requires Hammer PR

#698 Fixes #27778 - Org command no longer shows deprication warning
  lib/hammer_cli_katello/commands.rb
  lib/hammer_cli_katello/organization.rb
Labels: Needs testing, Not yet reviewed
