Repository Katello/hammer-cli-katello, pull requests merged in 2019-03, with the labels that each got.

#630 Fixes #26091 - Require product-id on cv update
  lib/hammer_cli_katello/content_view.rb
  test/functional/content_view/update_test.rb
Labels: Needs testing, Not yet reviewed

#632 Fixes #26047 - Add check for puppet in cvv export.
  lib/hammer_cli_katello/content_view_version.rb
  lib/hammer_cli_katello/cv_import_export_helper.rb
  test/functional/content_view/version/export_test.rb
Labels: Needs testing, Not yet reviewed

#633 Fixes #26326 - Fix export tar name to match cvv
  lib/hammer_cli_katello/content_view_version.rb
  test/functional/content_view/version/export_test.rb
Labels: Not yet reviewed

#634 Fixes #26447 - Remove version date from ostree info
  lib/hammer_cli_katello/ostree_branch.rb
Labels: Ready for merge, Requires Katello PR

#635 Fixes #26469 - Modular Info displayed for rpms
  lib/hammer_cli_katello/package.rb
Labels: Needs testing, Not yet reviewed
