Repository Katello/hammer-cli-katello, pull requests merged in 2020-09, with the labels that each got.

#740 Update Version to 0.23.0
  lib/hammer_cli_katello/version.rb
Labels: Ready for merge

#741 Bump master to 0.24 and update test api data
  lib/hammer_cli_katello/version.rb
  test/data/3.18/foreman_api.json
Labels: Ready for merge

#743 Fixes #30825 - Add back docker tag uploads with required params
  lib/hammer_cli_katello/repository.rb
  test/functional/repository/update_test.rb
Labels: Ready for merge

#744 Update test api data for 3.18 and update test helper to use 3.18 data
  test/data/3.18/foreman_api.json
  test/test_helper.rb
Labels: Ready for merge

#745 Bump version to 0.23.1
  lib/hammer_cli_katello/version.rb
Labels: Cherry-pick, Ready for merge

#739 Fixes #30735 - Add resolve traces command to Hammer
  lib/hammer_cli_katello/host_traces.rb
  test/functional/host/traces/resolve_test.rb
Labels: Needs testing, Not yet reviewed, Requires Katello PR

#746 Remove redundant text
  lib/hammer_cli_katello.rb
Labels: Ready for merge
