Repository Katello/hammer-cli-katello, pull requests merged in 2020-02, with the labels that each got.

#722 Fixes #28908 - Add pulp3 dep warning to repo create
  lib/hammer_cli_katello/repository.rb
  test/functional/repository/create_test.rb
Labels: Needs re-review

#726 Bump version to 0.22-master
  .gitignore
  lib/hammer_cli_katello/repository.rb
  lib/hammer_cli_katello/version.rb
  test/data/3.15/foreman_api.json
  test/data/3.16/foreman_api.json
  test/functional/host/extensions/update_test.rb
  test/test_helper.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#725 Fixes #29033 - added usergroups to search option creators
  lib/hammer_cli_katello/foreman_search_options_creators.rb
  test/unit/search_options_creators_test.rb
Labels: Needs testing, Not yet reviewed

#724 Bump to 0.21.0 for Katello 3.15
  .travis.yml
  hammer_cli_katello.gemspec
  lib/hammer_cli_katello/repository.rb
  lib/hammer_cli_katello/version.rb
  test/data/3.15/foreman_api.json
  test/functional/host/extensions/update_test.rb
  test/test_helper.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor
