Repository Katello/hammer-cli-katello, pull requests merged in 2020-01, with the labels that each got.

#714 Fixes #28293 - rename gpg command
  lib/hammer_cli_katello.rb
  lib/hammer_cli_katello/content_credential.rb
  test/functional/content_credentials/info_test.rb
  test/functional/content_credentials/list_test.rb
  test/functional/gpg_test.rb
Labels: Ready for merge

#715 Fix running unit tests locally
  test/functional/srpm/list_test.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#717 Fixes #28852 - Add Next Sync date in hammer command
  lib/hammer_cli_katello/sync_plan.rb
Labels: Ready for merge

#719 Fixes #28864 - Add policy to repo proxy info
  lib/hammer_cli_katello/repository.rb
Labels: Ready for merge

#716 Fixes #28833 - Add title resolver to organization resource
  lib/hammer_cli_katello/id_resolver.rb
  test/functional/organization/delete_test.rb
  test/functional/package/list_test.rb
Labels: Needs testing, Not yet reviewed

#720 Fixes #28294 - Create repo with ssl cert name
  lib/hammer_cli_katello/repository.rb
  test/functional/repository/create_test.rb
  test/functional/repository/data/test_ca.json
  test/functional/repository/data/test_cert.json
  test/functional/repository/data/test_key.json
Labels: Ready for merge

#721 Add aggregated product sync status
  lib/hammer_cli_katello/product.rb
Labels: Ready for merge
