Repository Katello/hammer-cli-katello, pull requests merged in 2022-07, with the labels that each got.

#855 Refs #35102 - Add SCA status check command
  lib/hammer_cli_katello/simple_content_access.rb
  test/data/4.6/foreman_api.json
  test/functional/simple_content_access/status_test.rb
Labels: Ready for merge

#856 Fixes #34861 - Syncable yum-format repository exports
  lib/hammer_cli_katello/content_export.rb
  lib/hammer_cli_katello/content_export_helper.rb
  test/data/4.6/foreman_api.json
  test/functional/content_export/complete/version_test.rb
  test/functional/content_export/generate_listing_test.rb
Labels: Needs testing, Not yet reviewed

#853 Fixes #34337 - CRUD simplified ACSs via hammer
  lib/hammer_cli_katello.rb
  lib/hammer_cli_katello/acs.rb
  test/functional/acs/create_test.rb
  test/functional/acs/delete_test.rb
  test/functional/acs/info_test.rb
  test/functional/acs/list_test.rb
  test/functional/acs/update_test.rb
Labels: Ready for merge, Requires Katello PR

#859 Refs #34861 - Ignore listing files for custom repos
  lib/hammer_cli_katello/content_export_helper.rb
Labels: Ready for merge
