Repository Katello/hammer-cli-katello, pull requests merged in 2023-05, with the labels that each got.

#888 Fixes #36284 - expose repository content label that could be overridden
  lib/hammer_cli_katello/repository.rb
  test/functional/repository/list_test.rb
Labels: Ready for merge

#887 Refs #36373 - Add metadata expire to repo info
  lib/hammer_cli_katello/repository.rb
Labels: Ready for merge, Requires Katello PR

#890 Add Katello 4.8 and 4.9 test data and fix tests
  .github/workflows/unit-tests.yml
  README.md
  test/data/4.8/foreman_api.json
  test/data/4.9/foreman_api.json
  test/test_helper.rb
Labels: Ready for merge

#893 Bump version to 1.9.0
  lib/hammer_cli_katello/version.rb
Labels: Waiting on contributor, Not yet reviewed

#892 Bump master to 1.10.0-master
  lib/hammer_cli_katello/version.rb
Labels: Waiting on contributor, Not yet reviewed
