Repository Katello/hammer-cli-katello, pull requests merged in 2025-02, with the labels that each got.

#981 Containerize hammer cli katello devel
  .github/workflows/development-container-release.yml
  Containerfile-devel
Labels: Waiting on contributor, Not yet reviewed

#982 Added a hammer devel container script
  README.md
  hammer-devel-container.sh
Labels: Waiting on contributor

#983 Clean up the container devel script
  Containerfile-devel
Labels: Waiting on contributor

#984 Remove warnings for ostruct, csv and syslog
  hammer_cli_katello.gemspec
Labels: Waiting on contributor, Needs re-review

#985 Bump master to 1.17.0-main
  lib/hammer_cli_katello/version.rb
Labels: Waiting on contributor, Not yet reviewed

#986 Release 1.16.0
  lib/hammer_cli_katello/version.rb
Labels: Waiting on contributor, Not yet reviewed
